### ISSUE TITLE
Speed up python manage.py populatedb

### ISSUE THREAD

**Issue by mspraggs** [ShaneDrury/pyon#6]
This currently takes... a while on a standard laptop, so optimization is really needed.

**Comment by ShaneDrury** [comment]
I wrote another parser (https://github.com/ShaneDrury/pyon-qed/commit/005a143b67f9eb770341fb93186b50f6c59211de) that doesn't use regex to try and speed it up. It didn't work.
I think this is due to the many different source/sink combinations in the files that we eventually chuck away. Since we only use about 4% of each file, there is a lot of time wasted processing things we'll never need. Probably a good option is to specify the source/sink/other parameters we want to keep and only process them. This may make regex processing viable.

**Comment by ShaneDrury** [comment]
Actually, I do think this belongs in pyon-qed. Moving.
https://github.com/ShaneDrury/pyon-qed/issues/2
